name: On MR

on:
  pull_request:
    branches:    
      - main 
      
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2 
        with: 
          submodules: true  
          fetch-depth: 0    

      - name: Setup node 
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
        
      - name: Install dependencies
        run: npm ci
      
      - name: Test project
        run: npm run test

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2 
        with: 
          submodules: true  
          fetch-depth: 0    

      - name: Setup node 
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
        
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build

